#!/bin/bash

# execute the crawlers
# On Ubuntu/Debian you can apt-get install libxml-libxml-perl and libxml-feed-perl if necessary

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR/crawlers"

perl -w feeds_to_html.pl 
perl -w html_to_page.pl
